<?php
$tr = array
(
    array
    (
        "your_score"=>"Твоя оцінка",
        "score"=>"Оцінка",
        "your_score"=>"Ваша оцінка:",
        "comment"=>"Коментувати",
        "retur"=>"Повернутись",
        "readme"=>"Прочитати",
        "topic"=>"Тема",
        "message"=>"Повідомлення",
        "reestr_tabl"=>"Заповніть реєстраційну таблицю",
        "data_indicated"=>"Поля відмічені ",
        "required"=>" обовязкові для заповнення",
        "enter_login"=>"Введіть свій логін",
        "enter_parol"=>"Введіть свій пароль(не менше 6 символів)",
        "_enter_parol"=>"Введіть свій пароль ще раз",
        "enter_email"=>"Введіть свій емаій",
        "enter_ima"=>"Введіть своє імя",
        "enter_bat"=>"Введіть імя по батькові",
        "enter_fam"=>"Введіть свою фамілію",
        "your_avatar"=>"Ваш аватар",        
        "users"=>"Користувачі",
        "golovna"=>"Головна",
        "forum"=>"Форум",
        "profil"=>"Мій профіль",
        "registr"=>"Реєстрація",
        "vuhod"=>"Вихід",
        "vhod"=>"Вхід",
        "res_parol"=>"Відновити пароль",
        "avtor_sait"=>"Автор сайту: Радчук Віталій",
        "napusatu"=>"Написати",
        "vidmina"=>"Відмінити",
        "redag"=>"Редагувати",
        "vudalutu"=>"Видалити",
        "dobavutu"=>"Добавити",
        "kilkist_korust"=>"Кількість користувачів на сайті:",
        "korust_online"=>"Користувачів онлайн:",
        "shanovnuy"=>"Шановний",
        "uspih_reg"=>"Ви успішно зареєстровались на сайті",
    ),
    array
    (
        "your_score"=>"Твоя оценка",
        "score"=>"Оцека:",
        "your_score"=>"Ваша оценка:",
        "comment"=>"Коментировать",
        "retur"=>"Возвратится",
        "readme"=>"Читать",
        "topic"=>"Тема",
        "message"=>"Сообщение",
        "reestr_tabl"=>"Заполните реестрационную форму",
        "data_indicated"=>"Поля отмеченые",
        "required"=>"обязательные для заполнения",
        "enter_login"=>"Введите свой логин",
        "enter_parol"=>"Введыте свой пароль(не мение 6 символов)",
        "_enter_parol"=>"Ведите свой пароль ищо раз",
        "enter_email"=>"Введите свой эмайл",
        "enter_ima"=>"Введите своё имя",
        "enter_bat"=>"Введите имя-отчество",
        "enter_fam"=>"Введите сваю фамилию",
        "your_avatar"=>"Ваш аватар", 
        "users"=>"Пользоватили",
        "golovna"=>"Главная",
        "forum"=>"Форум",
        "profil"=>"Мой профиль",
        "registr"=>"Реестрацыя",
        "vuhod"=>"Выход",
        "vhod"=>"Вход",
        "res_parol"=>"Востановить пароль",
        "avtor_sait"=>"Автор сайта: Радчук Виталий",
        "napusatu"=>"Написать",
        "vidmina"=>"Отмена",
        "redag"=>"Редактировать",
        "vudalutu"=>"Удалить",
        "dobavutu"=>"Добавить",
        "kilkist_korust"=>"Количество пользователей на сайте:",
        "korust_online"=>"Пользователей онлайн:",
        "shanovnuy"=>"Уважаемый",
        "uspih_reg"=>"вы успешно зарегистрировались на сайте",
        "login"=>"логін",
        "parol"=>"пароль",
    ),
    array
    (
        "your_score"=>"Your score",
        "score"=>"score:",
        "your_score"=>"your score:",
        "comment"=>"Comment",
        "retur"=>"return",
        "readme"=>"readme",
        "topic"=>"Topic",
        "message"=>"Message",
        "reestr_tabl"=>"Complete the registration table",
        "data_indicated"=>"Data indicated",
        "required"=>"required",
        "enter_login"=>"Enter your login",
        "enter_parol"=>"Enter your password (not less than 6 characters)",
        "_enter_parol"=>"Enter your password again",
        "enter_email"=>"Enter your email",
        "enter_ima"=>"Enter your name",
        "enter_bat"=>"Enter your last name",
        "enter_fam"=>"Enter your name and patronymic",
        "your_avatar"=>"Your avatar", 
        "users"=>"Users",
        "golovna"=>"Home",
        "forum"=>"Forum",
        "profil"=>"Profile",
        "registr"=>"Registration",
        "vuhod"=>"Exit",
        "vhod"=>"Entrance",
        "res_parol"=>"Recover password",
        "avtor_sait"=>"Author Site: Radchuk Vitaliy",
        "napusatu"=>"Write",
        "vidmina"=>"Cancel",
        "redag"=>"Edit",
        "vudalutu"=>"Remove",
        "dobavutu"=>"Add",
        "kilkist_korust"=>"Number of users in saite:",
        "korust_online"=>"Users online:",
        "shanovnuy"=>"Respected",
        "uspih_reg"=>"you have successfully registered on the site",
        "login"=>"Login",
        "parol"=>"Password",
    ),
);
?>